# Generated by Django 4.2.3 on 2023-12-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment_service",
            name="reference",
            field=models.CharField(default=7839467209, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment_service",
            name="status",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment_service",
            name="paystack_detail",
            field=models.JSONField(),
        ),
    ]
