# Generated by Django 4.2.3 on 2023-12-31 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "paymentApp",
            "0002_payment_service_reference_payment_service_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="payment_service", name="paystack_detail",),
        migrations.RemoveField(model_name="payment_service", name="reference",),
        migrations.RemoveField(model_name="payment_service", name="status",),
    ]
