# Generated by Django 4.2.3 on 2024-01-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentApp", "0003_remove_payment_service_paystack_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment_service",
            name="reference",
            field=models.CharField(default=789808978967675, max_length=50),
            preserve_default=False,
        ),
    ]
