# Generated by Django 4.2.3 on 2023-08-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicesApp", "0002_alter_service_service_option_bookingservice"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookingservice", name="service_option",),
        migrations.AddField(
            model_name="bookingservice",
            name="service_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="servicesApp.service",
            ),
            preserve_default=False,
        ),
    ]
