# Generated by Django 4.2.3 on 2023-09-04 13:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("servicesApp", "0005_patientmedicalhhistory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PatientMedicalHHistory", new_name="PatientMedicalHistory",
        ),
    ]
