# Generated by Django 4.2.3 on 2023-09-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesApp", "0006_rename_patientmedicalhhistory_patientmedicalhistory"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookingservice", name="patient_status",),
        migrations.RemoveField(model_name="bookingservice", name="served",),
        migrations.RemoveField(
            model_name="patientmedicalhistory", name="service_name",
        ),
        migrations.AddField(
            model_name="patientmedicalhistory",
            name="served",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
